//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPresentations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Presentations = new HashSet<Presentation>();
        }
    
        public int TagId { get; set; }
        public string Text { get; set; }
    
        public virtual ICollection<Presentation> Presentations { get; set; }
    }
}
